# Generated by Django 5.1.1 on 2024-11-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbr_srv_side', '0002_server_server_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedServerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_information', models.JSONField(verbose_name='host_information')),
                ('network', models.JSONField(verbose_name='network')),
                ('disk', models.JSONField(verbose_name='disk')),
                ('memory', models.JSONField(verbose_name='memory')),
                ('cpu', models.JSONField(verbose_name='cpu')),
                ('load_average', models.JSONField(verbose_name='load average')),
            ],
            options={
                'verbose_name': 'extended-server-info',
                'managed': True,
            },
        ),
    ]
