# Generated by Django 5.1.1 on 2024-11-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbr_srv_side', '0003_extendedserverinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedserverinfo',
            name='load_average',
            field=models.JSONField(verbose_name='load_average'),
        ),
    ]
